language: node_js

node_js:
  - "9"

cache:
  directories:
    - "node_modules"

before_deploy:
  - npm run build

deploy:
  provider: heroku

  api_key:
    secure: $HEROKU_API_KEY

  app: topln-ru

  strategy: git

  on:
    branch: master
